version: "3"
services:
  postgres:
    image: postgres:10.5
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sh:/docker-entrypoint-initdb.d/create_tables.sh

#  discovery:
#    image: developer.okta.com/microservice-docker-discovery:0.0.1-SNAPSHOT
#    ports:
#      - 8761:8761
# ----------------------------------------------------------------------------------------------------------------------------------
  users:
    image: modules/pitchuserservice:0.0.1-SNAPSHOT
    volumes:
      - ./config-data:/var/config-data
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
        -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - postgres
    ports:
      - "8081:8081"



# # ---------------------------------------------------------------------------------------------------------------------------------------------

  pitch-service:
    image: modules/pitchservice:0.0.1-SNAPSHOT
#    environment:
#      - JAVA_OPTS=
#        -DEUREKA_SERVER=http://discovery:8761/eureka
    volumes:
      - ./config-data:/var/config-data
    depends_on:
#      - users
      - postgres
    ports:
      - "10001:10001"

# ----------------------------------------------------------------------------------------------------------------------------------------------
# CHAT APPLICATION
# ----------------------------------------------------------------------------------------------------------------------------------------------

# ======================
# CHAT MESSAGING SERVICE
# ======================
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=password
#      - MONGO_INITDB_DATABASE=chatService
  #   volumes:
  #     - ./mongo-data:/data/db
  chat_messaging:
    depends_on:
      - mongo
    image: modules/chat-messaging:0.0.1-SNAPSHOT
    ports:
      - "8018:8018"
    environment:
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US.UTF-8"
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=chatService
      # - SPRING_DATA_MONGODB_USERNAME=admin
      # - SPRING_DATA_MONGODB_PASSWORD=password

# ======================
# CHAT CLIENT
# ======================
  chat_client:
    image: modules/chat-client:0.0.1-SNAPSHOT
    ports:
      - 3000:3000
    depends_on:
      - chat_messaging

# ======================
# CHAT AUTH SERVICE
# ======================
  chat_auth_services:
    image: modules/chat-auth-service:0.0.1-SNAPSHOT
    ports:
      - "8017:8017"
    environment:

      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US.UTF-8"
    depends_on:
      - mongo
