version: "3"
services:
  postgres:
    image: postgres:10.5
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sh:/docker-entrypoint-initdb.d/create_tables.sh
    networks:
      - my-proxy-net


  users:
    image: modules/pitchuserservice:0.0.1-SNAPSHOT
    volumes:
      - ./config-data:/var/config-data
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
        -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - postgres
    ports:
      - "8081:8081"
#    networks:
#      - my-proxy-net





  # # ---------------------------------------------------------------------------------------------------------------------------------------------

  pitch-service:
    image: modules/pitchservice:0.0.1-SNAPSHOT
    #    environment:
    #      - JAVA_OPTS=
    #        -DEUREKA_SERVER=http://discovery:8761/eureka
    volumes:
      - ./config-data:/var/config-data
    depends_on:
      #      - users
      - postgres
    ports:
      - "10001:10001"
    networks:
      - my-proxy-net


  #  pitch-messaging:
#    image: modules/pitchmessaging:0.0.1-SNAPSHOT
#    #    environment:
#    #      - JAVA_OPTS=
#    #        -DEUREKA_SERVER=http://discovery:8761/eureka
#    volumes:
#      - ./config-data:/var/config-data
#    depends_on:
#      #      - users
#      - postgres
#    ports:
#      - "10001:10001"

  frontend:
    image: pitchit/frontend:latest
    restart: always
    depends_on:
      - users
      - postgres
    ports:
      - "80:80"

  mongo:
    restart: always
    image: mongo:4.4.6
    expose:
      - 27017
    networks:
      - my-proxy-net

  chat_auth_services:
    image: modules/auth-service:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US.UTF-8"


networks:
  my-proxy-net:
    external:
      name: application-proxy