set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE pitchit;
    CREATE USER dev WITH ENCRYPTED PASSWORD 'dev';
    GRANT ALL PRIVILEGES ON DATABASE TO pitchit;
EOSQL