version: '3.8'
services:
  chat_auth_services:
    image: modules/auth-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8082"
    environment:
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US.UTF-8"
    networks:
      - my-proxy-net

  mongo:
    restart: always
    image: mongo:4.4.6
    expose:
      - 27017
    networks:
      - my-proxy-net