version: '3.8'
services:
  mongo:
    image: mongo:latest
    expose:
      - 27017
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=chatService
  #   volumes:
  #     - ./mongo-data:/data/db
  chat_messaging:
    depends_on:
      - mongo
    image: modules/chat-messaging:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US.UTF-8"
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=chatService
      # - SPRING_DATA_MONGODB_USERNAME=admin
      # - SPRING_DATA_MONGODB_PASSWORD=password
