spring:
  data:
    mongodb:
      host: mongo
      database: instaclone_auth
      port: 27017
    embedded:
      version: 3.2.22


  main:
    allow-circular-references:
      true
  server:
  port: 8081
      
security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic