services:
  db:
    image: postgres:14.1-alpine
    restart: always
    user: root
    environment:
      - POSTGRES_PASSWORD=D3Vel0pM3nT
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local